# Generated by Django 5.0.1 on 2024-10-03 00:32

from django.db import migrations


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogPost",
            fields=[],
            options={
                "managed": False,
            },
        ),
    ]
